services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    env_file:
      - .env

    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: study_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d study_app"]
      interval: 3s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
