// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"study-gin-clerk/internal/config"
	"study-gin-clerk/internal/handler"
	"study-gin-clerk/internal/infra/ai"
	"study-gin-clerk/internal/infra/db"
	"study-gin-clerk/internal/infra/repository"
	"study-gin-clerk/internal/router"
	"study-gin-clerk/internal/service"
)

// Injectors from wire.go:

func InitializeApp(cfg config.Config) (*gin.Engine, error) {
	healthHandler := handler.NewHealthHandler()
	gormDB, err := db.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	userProfileRepository := repository.NewUserProfileRepository(gormDB)
	userService := service.NewUserService(userProfileRepository)
	userHandler := handler.NewUserHandler(userService)
	chatRepository := repository.NewChatRepository(gormDB)
	userAPIKeyRepository := repository.NewUserAPIKeyRepository(gormDB)
	modelRegistry := ai.NewModelRegistry()
	memoryCache := ai.NewMemoryCacheDefault()
	userAPIKeyService := service.NewUserAPIKeyService(userAPIKeyRepository, modelRegistry, memoryCache, cfg)
	client := ai.NewClient()
	chatService := service.NewChatService(chatRepository, userAPIKeyService, client, userProfileRepository)
	chatHandler := handler.NewChatHandler(chatService)
	userAPIKeyHandler := handler.NewUserAPIKeyHandler(userAPIKeyService)
	aiHandler := handler.NewAIHandler(userAPIKeyService)
	dependencies := router.Dependencies{
		HealthHandler:     healthHandler,
		UserHandler:       userHandler,
		ChatHandler:       chatHandler,
		UserAPIKeyHandler: userAPIKeyHandler,
		AIHandler:         aiHandler,
	}
	engine := router.New(dependencies)
	return engine, nil
}
