// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"study-gin-clerk/internal/chat"
	"study-gin-clerk/internal/config"
	"study-gin-clerk/internal/health"
	"study-gin-clerk/internal/infra/ai"
	"study-gin-clerk/internal/infra/crypto"
	"study-gin-clerk/internal/infra/db"
	"study-gin-clerk/internal/router"
	"study-gin-clerk/internal/user"
)

// Injectors from wire.go:

func InitializeApp(cfg config.Config) (*gin.Engine, func(), error) {
	gormDB, cleanup, err := db.NewDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	handler := health.NewHandler(gormDB)
	repository := user.NewRepository(gormDB)
	modelRegistry := ai.NewModelRegistry()
	memoryCache, cleanup2 := ai.NewMemoryCacheDefault()
	aesCipher, err := crypto.ProvideCipher(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	service := user.ProvideService(repository, modelRegistry, memoryCache, aesCipher)
	userHandler := user.NewHandler(service)
	chatRepository := chat.NewRepository(gormDB)
	client := ai.NewClient(cfg)
	chatService := chat.ProvideService(chatRepository, client, modelRegistry, memoryCache)
	chatHandler := chat.NewHandler(chatService, service)
	dependencies := router.Dependencies{
		Config:        cfg,
		HealthHandler: handler,
		UserHandler:   userHandler,
		ChatHandler:   chatHandler,
	}
	engine := router.New(dependencies)
	return engine, func() {
		cleanup2()
		cleanup()
	}, nil
}
